# # Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению. 
# # Некоторые шаблоны требуют предварительной настройки перед запуском.
# #
# # Подробнее о синтаксисе можно узнать в документации:
# # https://docs.gitflic.space/cicd/gitflic-ci-yaml

stages:
  - build
  # - test
  # - deploy


build app:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  tags:
    - docker

unit tests:
  image: python:3.8.20-alpine3.20
  stage: test
  before_script:
    - python -m venv .venv
    - . ./venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/unit_tests
  needs: [ build app ]


# functional tests:
#   stage: test
#   variables:
#     - DOCKER_REGISTRY_LOGIN: $DOCKER_REGISTRY_LOGIN
#     - DOCKER_REGISTRY_PASSWD: $DOCKER_REGISTRY_PASSWD
#   before_script:
#     - docker run -d -p 5000:5000 --network=host "$DOCKER_REGISTRY_LOGIN/$CI_PROJECT_NAME:latest"
#     - docker pull selenium/standalone-chrome
#     - docker run -d -p 4444:4444 -p 7900:7900 --network=host selenium/standalone-chrome:latest
#   script:
#     - python3 -m venv .venv
#     - .venv/bin/pip install --upgrade pip
#     - .venv/bin/pip install pytest selenium
#     - .venv/bin/pytest tests/functional_tests
#   needs: [ build app, unit tests ]


# Publish Docker app:
#   stage: deploy
#   variables:
#     - DOCKER_REGISTRY_LOGIN: $DOCKER_REGISTRY_LOGIN
#     - DOCKER_REGISTRY_PASSWD: $DOCKER_REGISTRY_PASSWD
#   before_script:
#     - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWD"
#   script:
#     - echo "Publishing $CI_PROJECT_NAME docker image to $DOCKER_REGISTRY_LOGIN"
#     - docker push "$DOCKER_REGISTRY_LOGIN/$CI_PROJECT_NAME:latest"
#   needs: [ functional tests, unit tests ]