# # Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению. 
# # Некоторые шаблоны требуют предварительной настройки перед запуском.
# #
# # Подробнее о синтаксисе можно узнать в документации:
# # https://docs.gitflic.space/cicd/gitflic-ci-yaml

stages:
  - build
  - test


.install_firefox_geckodriver: &install_firefox_geckodriver
  - apt-get update && apt-get upgrade --assume-yes
  - apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils --assume-yes
  - wget -nv -O ~/FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64"
  - tar xjf ~/FirefoxSetup.tar.bz2 -C /opt/
  - ln -s /opt/firefox/firefox /usr/lib/firefox
  - export PATH=$PATH:/opt/firefox/
  - wget -nv -O ~/geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz"
  - tar -zxvf ~/geckodriver.tar.gz -C /opt/
  - export PATH=$PATH:/opt/


build app:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  tags:
    - docker

unit tests:
  image: python:3.8.20-alpine3.20
  stage: test
  before_script:
    - python -m venv .venv
    - . ./.venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/unit_tests
  tags:
    - docker
  needs: [ build app ]


# functional tests:
#   stage: test
#   before_script:
#     - docker run -d -p 5000:5000 --network=host "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
#     - docker pull selenium/standalone-chrome
#     - docker run -d -p 4444:4444 -p 7900:7900 --network=host selenium/standalone-chrome:latest
#   script:
#     - python3 -m venv .venv
#     - .venv/bin/pip install --upgrade pip
#     - .venv/bin/pip install pytest selenium
#     - .venv/bin/pytest tests/functional_tests
#   needs: [ build app, unit tests ]


functional tests:
  image: python:3.8
  stage: test
  services:
    - selenium/standalone-firefox:latest
  script:
    - *install_firefox_geckodriver
    - python -m venv .venv
    - . ./.venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install selenium
    - pytest tests/functional_tests
  needs: [ build app, unit tests ]
  tags:
    - docker