# Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению. 
# Некоторые шаблоны требуют предварительной настройки перед запуском.
#
# Подробнее о синтаксисе можно узнать в документации:
# https://docs.gitflic.space/cicd/gitflic-ci-yaml

stages:
  - build
  - test

name 1:
  stage: build
  script:
    - echo "Hello world!" > hello.txt

name 1.1:
  stage: build
  script:
    - echo "Hello world 1.1!" > hello.txt
  needs: [ name 1 ]

name 2:
  stage: test
  script:
    - echo "Goodbye world!"